### PR TITLE
Added 'auto rotate' settings in preference screen as per request 226 in tracker

### PR DESCRIPTION
**Pull request by riyaz**
implemented enhancement http://code.google.com/p/android-xbmcremote/issues/detail?id=226

### CODE REVIEW

**Comment by riyaz** [comment]
not sure how to ignore the line ending diff in my eclipse, ignore the white space diffs

**Comment by freezy** [comment]
Hey, thanks for the patch (and sorry for the ridiculously long response). Unfortunately, when running it on Android 2.1, I'm getting the following exception in any list view:

```
java.lang.NoSuchMethodError: android.widget.AbsListView.setAdapter
    at org.xbmc.android.remote.presentation.controller.ListController$3.run(ListController.java:186)
    at android.os.Handler.handleCallback(Handler.java:609)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:123)
    at android.app.ActivityThread.main(ActivityThread.java:4595)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:521)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by freezy** [comment]
Hmm, when reverting the Android reference in Eclipse from 4.0.3 to 2.3.3, it seems to work. Can you confirm your tests with 2.3.3? Any reason why you set it to 4.0.3?

**Comment by riyaz** [comment]
Opps, looks like some SDK issue, I have tested in my ICS device so I gave it as 4.0.3, I will verify with 2.3.3 and update the results.

**Comment by riyaz** [comment]
App works fine with 2.3.3, have been using my modified for few few found no issues with the fix.

**Comment by freezy** [comment]
Ok, cool. Do you want to update the pull request so it merges, otherwise I'll try later.

**Comment by riyaz** [comment]
Updated the project.properties, below changes are required for the fix, it has some line ending diffs, which should be ignored

ac31be8 
da94aba
04d3d02
5ce2a0a
